- scripts/builder.js
Running `scripts/builder.js` on different file systems may result in different ordering of the snippets in `README.md` depending on what order the OS returns the array of files in `fs.readFileSync`. Using a custom case-insensitive comparator will ensure consistency when building on different environments.
> Sort snippets with case-insensitivity

- README.md
- snippets/get-scroll-position.md
Get the current distance scrolled by `window` or `HTMLElement` as an {x,y} object.
I use this often for simple scroll based interactions/triggers
[Codepen demo](https://codepen.io/ohsimtabem/pen/MrWpmd)
> Add getScrollPos of HTMLElement / window

- snippets/value-or-default.md
Useful when you get value from a server that is falsy  eg. `undefined, null, NaN`
> Add value or default

- snippets/chain-async-functions.md
I included a "long form" as well. I think providing an explanation in this way may be very helpful to beginners, for whom this is a great resource. GitHub's `<details>` functionality is a little-known secret.
> Added async function chain

- README.md
- snippets/anagrams-of-string-(with-duplicates).md
It is good practice to keep map/filter/reduce side-effect free. This PR removes the impure `.push` inside `.map` and instead returns a new array concatenated from the accumulator and the recursive `anagrams` call.
> Make "Anagrams of string" fully functional

- snippets/curry.md
altough certainly more verbose, this version accounts for variadic functions such as Math.min that can't represent it's arity with the length property properly. for such cases you can pass the optional argument arity (as in the edited example).
what do you think?
> refactor curry to account for variadic functions

- snippets/measure-time-taken-by-function.md
I thought the spread syntax was kinda odd, so I opened this pull request to adopt the more common callback style. Discussion welcome.
One potential benefit of this is that the callback can be stored in a separate variable, allowing you to pass the variable to the function timeTaken() directly. You can also pass parameterless functions directly without wrapping them in another arrow function.
> Refactor measure-time-taken-by-function from spread syntax to callback function

- README.md
- snippets/compact.md
similar to lodash compact method
Use `.filter()` to filter falsey values. For example false, null, 0, "", undefined, and NaN are falsey.
`compact([0, 1, false, 2, '', 3, 'a', 'e'*23, NaN, 's', 34]) -> [ 1, 2, 3, 'a', 's', 34 ]`
https://lodash.com/docs/4.17.4#compact
> add compact.md & ran npm run build-list

- snippets/get-ordinal-suffix-of-number.md
JS Code Snippet to get the ordinal suffix of a given number (int or string).
Returns the provided value wtih concatenated ordinal.
I made it as small as I thought I could to make it easier to read and simply use includes to find pattern matches.
> Get Ordinal Suffix of Number

- README.md
- snippets/validate-number.md
now passes all 16 test cases:
```js
[
validateNumber('10') // true
,!validateNumber(false) // false
,!validateNumber(true) // false
,validateNumber(10) // true
,validateNumber(0.10) // true
,validateNumber(010) // true
,validateNumber(0xA) // true
,!validateNumber(NaN) // false
,!validateNumber(null) // false
,!validateNumber(undefined) // false
,!validateNumber('10%') // false, % is a construct
,!validateNumber('10px') // false
,!validateNumber(Infinity) // false
,validateNumber(Math.PI) // true, but is such an extreme edge case...
,validateNumber(0) // true, will probably wreck things
,validatenumber(1e10) // true
]
```
> Fix: validateNumber: check cooercian

- snippets/pipe.md
Now pipe's first function can accept an arbitrary number of arguments; every subsequent function must be unary. The arguments to reduce also use 'f' and 'g', which makes pipe more intuitive to read as it closely resembles its mathematical background.
> Rewrote pipe such that the first function may have any arity.

- snippets/array-zip.md
- snippets/compose-functions.md
- snippets/compose.md
- snippets/pipe.md
Compose's last (rightmost) function can accept an arbitrary number of arguments; every subsequent function must be unary. The arguments to `Array.reduce()` also use 'f' and 'g', which makes pipe more intuitive to read as it closely resembles its mathematical background.
Also added spread operator into explanation of pipe.
> Added compose such that the rightmost function may have any arity.

- snippets/array-includes.md
there is a function available in ES6 that works like this:
```js
let arr = [ 1,2,3,4,5,6 ]
arr.includes(4) // -> true
```
and it also works for strings 
```js
"30-seconds-of-code".includes("code") // -> true
```
and I think we should avoid native javascript method names like `includes`.
maybe I should add a PR to resolve that issue too.
> edit Array includes description

- snippets/compact.md
Make compact a bit more compact by not creating an arrow function.
> Use Boolean for compact

- README.md
- snippets/array-pull-(mutates-array).md
This PR fixes "Array pull" as it mutates not with pulled values but values we want to pull out.
Before:
```
let myArray = ['a', 'b', 'c', 'a', 'b', 'c'];
pull(myArray, 'a', 'c');
console.log(myArray) -> [ 'a', 'c', 'a', 'c' ];
```
After:
```
let myArray = ['a', 'b', 'c', 'a', 'b', 'c'];
pull(myArray, 'a', 'c');
console.log(myArray) -> [ 'b', 'b' ];
```
> Fix Array pull (mutates array) to pull out values correctly

- snippets/hexToRGB.md
Here's how new and old function results compare.
> hexToRgb: Fix returning wrong value for short hash without # symbol, fix extendHex called 3 times

- snippets/nthElement.md
I changed the name of the function, inserted a comma and changed the index of the second call to the function, in order for it to give the expected result.
> Fix `nthElement'-example.

- snippets/initializeArrayWithRange.md
Behavior should stay consistent. if `start = 0` and `0` gets mapped/initialized I believe `end` should also mapped/initailized like so. If both arguments are inclusive, or inclusive and/or exclusive I think it should say in the description. My assumption however is that the function arguments `start` and `end` are both inclusive 
```js
initializeArrayWithRange(5) //-> [0,1,2,3,4,5]
initializeArrayWithRange(7, 3) //-> [3,4,5,6,7]
```
However that is not the case and when the arrayRange gets initialized only the start is initialized with the array
```js
const initializeArrayWithRange = (end, start = 0) =>
Array.from({ length: end - start }).map((v, i) => i + start);
// initializeArrayWithRange(5) -> [0,1,2,3,4]
// initializeArrayWithRange(7, 3) -> [3,4,5,6]
```
Simple `(end + 1)` fix should …
> fix/update intializeArrayWithRange.md

- snippets/pull.md
- snippets/without.md
This adds references to the other functions for people to see implementations that mutate/don't mutate the original arrays.
> Add references to #pull/#without

- snippets/pullAtIndex.md
- tag_database
similar to lodash pullAt method
But I decided to call it pullAtIndex since when using this function before in the past felt weird since the name when compared to using other lodash  `_.pull` method made me assume it was using values. Think having a `pullAtIndex()` which does pull and returns based on index & `pullAtValue()` which does pull and returns based on value would def add value. What do you think @Chalarangelo  
This method is like pull except that it accepts an array of indexes to filter out before Mutating and pulling all the values from the original array. Which then returns an array of removed elements.
Use `Array.filter()` and `Array.includes()` to pull out the values that are not needed.
Use `Array.length = 0` to mutate the passed in array by resetting it's length to zero …
> Add pullAtIndex

- CONTRIBUTING.md
Fix the typo for the script `npm run build-list` when it should actually be -> `npm run builder`
> Update CONTRIBUTING.md -> fix npm run typo

- README.md
- snippets/compact.md
The Compact snippet was the only example where a single argument of a fat-arrow function was wrapped with a parenthesis.
* [`compact`](#compact)
> [ENHANCEMENT] Removed unique occurrence of wrapping a single argument function with parenthesis

- tag_database
Moves Promisify over to the Adapter category. I have tried ot rebuild but for some reason when I build the Adapter category does not appear
> [ENHANCEMENT] Move Promisify to the Adapter category

- snippets/toSnakeCase.md
- tag_database
Converts a string to snakecase.
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#snakeCase
> [FEATURE] Add toSnakeCase

- snippets/randomHexColorCode.md
The current version has a 1:16 probability of generating a 5-digit colorcode. The edited snippet adds a random hexadecimal digit as prefix in case the generated code is only 5 digits long.
**Resolves** #355
> [FIX: #355][randomHexColorcode.md] Fix 5-digit issue 

- snippets/shuffle.md
The implementation of `shuffle` was changed from an in-place function into a pure function, but the documentation was not updated, so I've updated the docs to mention that it returns a new array instead of shuffling the input in place.
Follow-up to https://github.com/Chalarangelo/30-seconds-of-code/pull/358
> Fix documentation for shuffle

- snippets/isArrayLike.md
- snippets/isValidJSON.md
**Lodash[ADD]** #100 -> https://lodash.com/docs/4.17.4#isArrayLike
> [ADD : isArrayLike.md and isValidJSON.md]

- snippets/sortedIndex.md
**Lodash[ADD]** #100 -> https://lodash.com/docs/4.17.4#sortedIndex
> [ADD sortedIndex.md] 

- snippets/defer.md
- tag_database
**Lodash[ADD defer.md]** #100 -> https://lodash.com/docs/4.17.4#defer
> [ADD: `defer.md`] defer

- snippets/pluralize.md
- Allows for autopluralization with currying
- Allows any number. `-1` and `1` are considered "singular". Actually should -1 be plural? I don't really know. It doesn't make sense to pluralize negatives, but I feel like it shouldn't throw an error at all. It also coerces strings etc to a number to make life easier.
> [UPDATE] pluralize.md

- snippets/partition.md
- tag_database
**Lodash** #100 -> https://lodash.com/docs/4.17.4#partition
> [FEATURE] Add partition

- snippets/forOwn.md
- snippets/forOwnRight.md
- tag_database
Two methods for objects from lodash.
**Lodash[ADD]** #100 -> https://lodash.com/docs/4.17.4#forOwn
**Lodash[ADD]** #100 -> https://lodash.com/docs/4.17.4#forOwnRight
> [FEATURE][ADD] Add forOwn and forOwnRight

- snippets/tomorrow.md
Fix a problem due to the assumption that days are always 24 hours long, while due to DST one day a year is 23 hours and one day a year is 25 hours long. This lead this function to give the current date during one hour a year and the day after tomorrow for another hour a year.
Additionally, the function only worked correctly when the user was in the same timezone as UTC. For example in Amsterdam which 1 hour from DST it only worked 23 hours a day. And in Sydney which is 11 hours away from DST, the function only worked correctly for 13 hours each day. During the hours it didn't work correctly it would give the current date instead of tomorrows.
**Resolves** #564
> [FIX: #564] Fix inaccurate tomorrow() function

- snippets/randomHexColorCode.md
- test/randomHexColorCode/randomHexColorCode.test.js
Now generating a random number, timesing it by 10^6 and converting it to hex. 
Test previously only checked was of type function, now checks return length is 7 (including `#`)
**Resolves** #580
> [FIX: #580] Fix randomHexColorCode() sometimes returning strings too short & Fix test for same snippet

- snippets/stableSort.md
- tag_database
- test/stableSort/stableSort.js
- test/stableSort/stableSort.test.js
Most browser engines support stable sorting via `Array.sort()` but not Chrome/NodeJS.
More information:
- [Wikipedia](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability)
- [Example](https://github.com/mziccard/node-timsort/#stability)
- [Implementation](https://gist.github.com/simov/aa3b9e534039fa00ac3c1b4905605069)
> [FEATURE][ADD] Add stableSort function

- static-parts/index-start.html
This PR improves the performance of the snippet search function on the website. The `search` was running slowly (~1 second per `keyup` event) due to forced reflows caused by alternating style reads and writes for each iteration of its internal loops. For example, on each iteration through the loop of snippet nodes, there was a style read due to calling `x.innerText` on a DOM node, then a style write due to `x.style.display = ...`. This forced a reflow on each time through the loop, slowing down the total time taken to search through all nodes for matches. This profile depicts one call of `search` with the argument `"if"` prior to the fix.
Instead, replacing `x.innerText` with `x.textContent` avoids forced reflows and allows the browser to batch all style updates when the loop finishes. …
> [WEB] Avoid forced reflows inside search function

- snippets/sortedLastIndex.md
- test/sortedLastIndex/sortedLastIndex.js
- test/sortedLastIndex/sortedLastIndex.test.js
Change the test of sortedLastIndex to expect a return value of 4 and stopped sortedLastIndex subtracting 1 before returning
**Resolves** #629
> [FIX:#629] Fix invalid test for sortedLastIndex & Fix sortedLastIndex

- snippets/copyToClipboard.md
As of now, the Clipboard API is still experimental. But nevertheless, this is how we will be implementing copy&paste&cut in JS in the future. 
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
https://github.com/w3c/clipboard-apis/blob/master/explainer.adoc#writing-to-the-clipboard
> Add new Clipboard API Disclaimer to copyToClipboard

- snippets/when.md
- tag_database
- test/when/when.js
- test/when/when.test.js
Inspired by [Ramda](http://ramdajs.com/docs/#when), I absolutely love this function. It's even better, however, if you compose it by only supplying the first two parameters.
That's why my implementation returns a function expecting `x`.
If accepted, would we consider currying this function? I think the answer's "no" based on [previous discussion](https://github.com/Chalarangelo/30-seconds-of-code/pull/646#issuecomment-380253755) that this is a learning library.
> Add when()

- snippets/palindrome.md
- test/palindrome/palindrome.js
- test/testlog
Currently, `palindrome` snippet doesn't use the same syntax as `reverseString`. I've updated palindrome's description as well as code to match more modern ES6ish syntax that `reverseString` uses. 
Ran tests, everything is fine. Nothing is broken 😉
> [ENHANCEMENT] Update palindrome

- snippets/reject.md
- tag_database
- test/reject/reject.js
- test/reject/reject.test.js
`Array.filter`'s complement. Whatever `filter` keeps, `reject` denies.
This repo's a great functional programming resource, but I surprisingly haven't encountered complementary functions yet. Maybe I haven't look hard enough, but it'd still be cool to contribute this 😁 .
> Add reject

- snippets/findLast.md
- test/findLast/findLast.js
Simplify findLast snippet [ENHANCEMENT]
Use native metho pop of array instead slicing and getting the last element.
> Simplify findLast snippet

- snippets/nodeListToArray.md
- test/nodeListToArray/nodeListToArray.js
Simplify nodeListToArray [ENHANCEMENT]
Spread operator is more declarative that Array.prototype.slice (with confusing Function.prototype.call) and modern.
> Using more declarative way to create array in nodeListToArray

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/feature_request.md
In reference to #730 
Simple, easy-to-use and less cluttered Issue templates. 
**Chore:** Remove the old `ISSUE_TEMPLATE.md` right after merging.
> Update issue templates

- snippets/mask.md
- test/mask/mask.js
As asked in https://github.com/30-seconds/30-seconds-of-interviews/pull/107#issuecomment-424019789, I'm making a pull request to the same changes merged in 30 seconds of interviews.
Using `String.padStart` we can make the `mask.md` snippet a bit simpler.
>  [ENHANCEMENT] Simpler solution to mask using padStart

- snippet_data/snippets.json
- snippets/shank.md
- tag_database
- test/shank/shank.js
- test/shank/shank.test.js
cc @brianboyko
---
Duplicates `Array.prototype.splice()` except returns a new array instead of mutating in-place
- [ X] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
> [FEATURE] shank()

- snippets/atob.md
- snippets/btoa.md
- test/atob/atob.js
- test/btoa/btoa.js
> [FIX] Replace deprecated calls in atob and btoa

- test/allEqual/allEqual.test.js
- test/tomorrow/tomorrow.js
Resolves #804 - Adds a test for allEqual.test.js with an array that have different types.
> [FIX] allEqual.test.js test arrays with different types in the same array

- snippets/sample.md
Updates 'Sample' snippet description text from '...round it of to the nearest' to '...round it off to the nearest'. Chaning 'of' to 'off'.
> [FIX] Updates typo in 'sample' snippet from 'of' to 'off'

- snippets/toTitleCase.md
- tag_database
I added a `toTitleCase` snippet to convert any string to its title-case equivalent.
It reuses the same "tokeniser" RegExp that is already featured in the `toCamelCase`, `toKebabCase` and `toSnakeCase` snippets.
> Add toTitleCase snippet and update tag_database accordingly

- snippets/shank.md
- snippets/toHash.md
The shank and toHash snippets mention the usage of `<Class>.prototype.prototype.method` with `prototype.prototype` when the actual code does only `prototype`. This PR fixes that typo.
> [FIX] docs: `prototype.prototype` -> `prototype`

- package.json
- scripts/module.js
Fixes #875 
- Module correctly builds UMD and ESM files. 
- Cleaned up the script.
- Add `"sideEffects: false` key to `package.json` for webpack tree-shaking support, i.e.
```js
import { snippet } from '30-seconds-of-code';
```
Won't bundle the other snippets as well since they're considered dead code
> [FIX] Module generation

- snippets/isNegativeZero.md
- tag_database
- test/isNegativeZero.test.js
I've added a handy utility snippet that checks whether a provided value is negative zero or not. 
Before you make a noise, let me explain a bit how JavaScript handles numbers and why is this function useful to some people.
```js
0 === -0 //  true
0 / 3 // equals to 0
0 / -3 // equals to  -0
Infinity === -Infinity // false
```
Yes. I know that negative zero doesn't exist in real Math but this is just how JavaScript engine threats it. Whenever JavaScript engine works with dividing negatives, it treats them as positives and adds `-` afterward.
Not much as you've guessed it but this function can be used when writing complex animations, a `-0` on just finished animation can provide information on whether the animation was coming from the right or the left side etc. 
I wrote the tests, they …
> [FEATURE] add isNegativeZero

- snippets/filterFalsy.md
- tag_database
- test/filterFalsy.test.js
FEATURE filterFalsy snippet
Add filterFalsy snippet that filters falsy elements from an array.
**BREAKING CHANGES**
*THE TESTS DON'T PASS*
The tdd script ```npm run tester``` doesn't work. It fails because of tests. Some unrelated tests seem to fail.
> add filterFalsy snippet, tags, and tests

- snippets/normalizeVector.md
- tag_database
This PR adds a snippet that normalizes a vector. The normalization process takes a vector and returns a second vector with the same direction, but a magnitude of 1.
> [FEATURE] add normalizeVector snippet

- snippets/chainAsync.md
- test/chainAsync.test.js
chainAsync update: last function shouldn't get 'next' as argument. That way it's easier to add a condition within the functions to check whether they're the last one, e.g. `if(next){/* is last function*/}else{/* isn't */}`. This is useful when the array of functions is generated, rather than hard-coded.
My tests pass, but the `npm` scripts outlined in the docs didn't update `test/_30.js`. Not sure what additional step is needed for that.
> [FEATURE] chainAsync update: last function shouldn't get 'next' as argument

- snippets/hashNode.md
It was something we forgot and that we don't want to forget. Sending it onto the event loop prevents us from blocking with a long operation, allowing other things on the event loop to happen before a take a possibly long time
Resolves #907 
We push the hashing onto the next tick and use a promise because the hash could take a long time to complete.
> [FIX] #907 Explain next tick logic on `hashNode`

- README.md
- static-parts/README-start.md
The title says it all - this change updates the readme and adds a 30-seconds-of-kotlin link.
> [ENHANCEMENT] Add related Kotlin project to README

- static-parts/page-start.html
- static-parts/static-page-start.html
FIX Search field algorithm
Remove display none at li tags instead of li > a
> Resolve issue #914 Search field

- snippets/minBy.md
Fixed a minor typo in `minBy` description that says "maximum" instead of "minimum"
> [FIX] Minor typo fix

- snippets/checkProp.md
- tag_database
Adds a simple utility function that allows for easy creation of predicate functions that inspect passed objects without passing the context to the predicate, allowing for simpler predicate functions, and easier composition.
> [FEATURE] add checkProp utility function for inspecting objects

- snippets/arrayToCSV.md
- test/arrayToCSV.test.js
Most CSV parsers understand strings to be wrapped in double quotes, and double-quotes within strings to be escaped with additional double quotes. In addition, values not enclosed in quotes should be interpreted as numeric.
This modifies the existing one-liner to provide this functionality. The function should now produce a CSV that can be parsed by any compliant reader for just about any kind of input.
> [ENHANCEMENT] arrayToCSV escape quotes in strings and un-quote numeric vals

- snippets/isNumber.md
- test/isNumber.test.js
> [FIX] #935 isNumber is wrong for NaN

- snippets/isEmpty.md
They use size instead of length
Remove some confusing and incorrect langauge
> Maps and Sets are not collections, but Stores

- snippets/drop.md
- snippets/dropRight.md
Fixing minor typos in the description from the drop and dropRight snippets. Fixed the use of slice and removed terms.
> Minor typo fixes with drop and dropRight snippets

- package.json
The `devDependencies` should not be at the top where we normally find the meta data like `name`, `version` and so on.
> Move devDependencies under dependencies

- snippets/maxDate.md
- snippets/minDate.md
- test/minDate.test.js
The functions already expect an array. There is no need to spread the argument and re-spread to use `apply`. This creates an unnecessary one-element array for no benefit. We could expect an array argument without spreading and then pass it directly to `apply`. But since we all encourage modern JS, using the spread syntax is better.
Resolves #984
> [ENHANCEMENT] Simplify min and max date functions

- snippets/compact.md
- snippets/findLast.md
- snippets/findLastIndex.md
- snippets/omitBy.md
- snippets/pickBy.md
- test/all.test.js
- test/compact.test.js
- test/dig.test.js
- test/omitBy.test.js
Previously, the word falsy is spelled sometimes as falsy, and sometimes as falsey (with an e). This pull request brings consistency by changing them all to falsy, as the array's FilterFalsy function is spelled without an e.
> FIX(snippet): Changing instances of the word falsey to falsy

- snippets/isWeekend.md
Since a weekend is either `0` or `6` from `Date#getDay()`, using `X % 6 === 0` will return the right Boolean value and lead to less function calls or comparisons.
Requires no changes to any tests as it still returns a boolean
> Simplify the comparison for a weekend

- snippets/findLastIndex.md
- test/_30s.js
- test/findLastIndex.test.js
> fix findLastIndex: return default index when not found

- src/docs/pages/index.js
- src/docs/styles/_layout.scss
My current working draft for the homepage, including a link to the snippet list, the org's boilerplate and links to all other project websites.
> Update homepage to act as a hub for projects

- snippets/ary.md
- test/ary.test.js
Modify firstTwoMax()'s input array [8, 4, 6] to [6, 4, 8] to make it clear that firstTwoMax only cares about the first 2 arguments.
> [ENHANCEMENT] Make the example for unary clearer

- config.js
- gatsby-node.js
- src/docs/components/SnippetCard.js
- src/docs/pages/archive.js
- src/docs/pages/index.js
- src/docs/pages/list.js
- src/docs/pages/search.js
- src/docs/templates/SnippetPage.js
- src/docs/templates/TagPage.js
After migrating this and other repositories to the new infrastructure, we realized that there are performance issues, mainly due to the way much of our codebase is structured and how all the moving parts come together. In order to solve this issue, I took the time to set up a custom schema in GraphQL, providing some major performance improvements, while also paving the way for future updates to the webite(s).
> Create custom 'Snippet' schema in GraphQL

- snippets/equals.md
[equals](https://github.com/30-seconds/30-seconds-of-code#equals-) snippet has redundant check for `undefined` & `null` values. Those values get checked in the previous conditionals.
That extra if condition can be safely removed without any breaking changes.
This PR removes that redundant if conditional from **equals** snippet. No tests need to be modified as the code removed was redundant and all tests pass without it.
> [ENHANCEMENT] Remove redundant condition from equals snippet

- src/docs/pages/index.js
the link for 30 seconds of knowledge was not working so I dove into this code base and found a working link to a chrome extension being used elsewhere and added that.
On this page (https://www.30secondsofcode.org), I replaced:
https://30secondsofknowledge.org/
with 
https://chrome.google.com/webstore/detail/30-seconds-of-knowledge/mmgplondnjekobonklacmemikcnhklla
- [X ] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
> [FIX] Link to 30 seconds of knowledge wasn't working on website

- snippets/hasKey.md
- test/hasKey.test.js
[hasKey](https://github.com/30-seconds/30-seconds-of-code#haskey) snippet is really handy to check for inner keys in nested objects. Unfortunately current implementation of it fails for a particular case:
(Where one key is prefix of another and it has object value, in this case `b` & `b.c`)
```
let obj = {
'a': 1,
'b': { 'e': 4 },
'b.c': 5
};
hasKey(obj, 'b.c');
// should return "true" but returns "false"
```
The above scenario can not be handled with current method signature of accepting second argument as string. Using function signature where it accepts Array of keys, we can address above scenario along with other simpler cases.
This also simplifies overall implementation of function without using any recursion or string manipulations. With Array as key list, we can use …
> [FIX] Update hasKey snippet to handle failing scenario and add new tests

- dist/_30s.es5.js
- dist/_30s.esm.js
- dist/_30s.js
- test/_30s.js
- test/luhnCheck.test.js
Resolves #1084.
As explained in the issue, the `acc + ((val * 2) % 9) || 9)` logic in the function makes it so if even if the acc should equal zero it gets set to 9, which messes up the rest of the calculation. You can see this happening here:
**PLEASE NOTE:** I wasn't able to find out how to properly update `_30s.es5.min.js`, every tool I used ending up adding extra quotes that would have changed a lot of the file rather than just the `luhnCheck` function. If someone could help me out with that it'd be great.
> [FIX] Correctly implement luhnCheck

- snippets/JSONToFile.md
fs.writeFile() must have a callback function,or it will throw a `TypeError`.
> Update: update JSONToFile.md

- snippets/unflattenObject.md
**The Issue(s)**
As shared in [issue#1175](https://github.com/30-seconds/30-seconds-of-code/issues/1175). The current code fails to restore nested properties and doesnot cater for scenairos like
```js
unflattenObject({ 'a.b': 1, 'a.c': 2, d: 3 })
unflattenObject({ 'a.b': 'foo', d: 3 })
```
where either the same key is being refered more than once or the values are non numbers. More detials can be seen in [this](https://runkit.com/tbasse/5f2a9929c9b5c9001a4d3a6e) runkit shared in the issue as well.
An additional scenario which the code failed to handle was when the flat path reffered to particular indices in the arrays values against a key. For example.
```js
unflattenObject({ 'a.b.0': 5, d: 3 })
```
should return something like `{a:{b:[5]}, d: 3}`. However, the code fails to compile. …
> Fix issue #1175 and cater additional scenarios

- snippets/normalizeLineEndings.md
- snippets/toTitleCase.md
- snippets/wordWrap.md
Added `wordWrap` snippet that adds break characters after words at a given maximum character. Also fixed typos in `normalizeEndings` and `toTitleCase` snippets.
> Added wordWrap snippet and fixed typos

- snippets/isSorted.md
Also add some style changes like using `Math.sign(direction)` instead of `direction / Math.abs(direction)`
> fix: allow for shorter arrays in isSorted

- snippets/frequencies.md
Since the `frequencies` snippet can be used to count char occurrences in strings as well, I added a new example to it
> Adds another example to frequencies snippet

- snippets/toHSLObject.md
In addition to [this PR](https://github.com/30-seconds/30-seconds-of-code/pull/1616) that adds `toHSLArray` I am adding a utility function to restructure it inside an object. 
I went with full `hsl` "component" names _(hue, saturation, lightness)_ due to code readability and use cases. For example, it would be much cleaner to say `lightness * 0.5` to make it darker than doing `l * 0.5` etc. PS I also vote we do this to [`toRGBObject`](https://www.30secondsofcode.org/js/s/to-rgb-object).
Anyways to celebrate 2000 followers on our Twitter bot we made a year ago, I got this Greek candy:
> add toHSLObject

- snippets/toRGBObject.md
based on this [discussion](https://github.com/30-seconds/30-seconds-of-code/pull/1617#issuecomment-710416336) I am changing RGB object key names to something more meaningful (believe it or not, some folks don't know what values `r`, `g`, `b` stand for). It also follows the same naming pattern as `toHSLObject`. 
```diff
- {r: 255, g: 12, b: 0}
+ {red: 255, green: 12, blue: 0}
```
> cleaner names inside toRGBObject

- snippets/initializeArrayWithRange.md
Since argument v was unnecessary, it can be replaced with _.
> Use underscore for unused argument

- snippets/changeLightness.md
- snippets/lighten.md
as previously discussed with @Chalarangelo I am adding a `changeLightness` snippet to provide more value to folks who are working with color. 
**Yes.** it's a simple modification of `hsl` values but too many this color theory is [_That's Greek to me._](https://en.wikipedia.org/wiki/Greek_to_me)
_**use case:**_
Modifying a single value could be done by hand, but to achieve things dynamically a user needs a method like `changeLightness`. Here is an example of dynamically generated user icons like we see on Figma or Google Docs etc.
> add changeLightness snippet

- snippets/bubbleSort.md
Bubble sort is not working properly.
The following returns `[2, 1, 3, 4]` instead of `[1, 2, 3, 4]`
```
bubbleSort([4, 3, 2, 1])
```
Pull request fixes this bug.
> Fix bubbleSort

- snippets/python/s/is-perm.md
- snippets/python/s/iterable-is-permutation.md
Added is-perm, a quick efficient way to check that two iterables are permutations of each other.
> Added is-perm

- README.md
The website heading reads, "Discover short code snippets for all your development needs." The block quote specifies, "Short JavaScript code snippets for all your development needs" differing slightly from the main heading.It also does not match the tagline on the image of Readme.
> Update README.md . Block quote not matching 30secondsofcode website's heading.

- content/snippets/js/s/event-loop-explained.md
Fixes #2015 
This PR fixes a typo in the explanation in line 96. The callback of `Promise.prototype.then()` was queued in step 9, not step 10.
> Issue #2015 Fix typo in event loop explanation

- content/snippets/js/s/data-structures-queue.md
Fixes #2019 
This PR removes the unnecessary, unused `item` parameter in the `dequeue()` and `peek()` methods of the Queue class in lines 38 and 42. 
Additionally, a slight elaboration is made in line 53 below, to specify that the element being added by the `enqueue()` method is the `item` argument that's passed in during function invocation.
> Fix unnecessary parameters in Queue class method and elaborated on explanation

- src/blocks/application.js
- src/blocks/utilities/preparedQueries.js
Introduce a `PreparedQueries` utility to allow commonly-used queries to be set up in such a way that they can be used from the REPL console quickly and easily. Includes automatic caching to increase performance on long queries.
> Set up infrastructure for prepared queries

- package.json
- src/blocks/application.js
- src/blocks/extractor/extractor.js
- src/blocks/utilities/fileWatcher.js
- src/blocks/writers/pageWriter.js
- src/scripts/develop.js
- src/scripts/watch.js
- First stage of a HMR for content files. 
- Supports changes to snippet files only, regenerating the relevant page data.
- Can be run with `npm run watch` while the Astro dev server is up. 
- Requires manual reloading of the page in the browser.
> Watch mode - Snippets

- .github/workflows/test.yml
Potential fix for [https://github.com/Chalarangelo/30-seconds-of-code/security/code-scanning/24](https://github.com/Chalarangelo/30-seconds-of-code/security/code-scanning/24)
To fix the issue, we will add a `permissions` block to the workflow. Since the workflow only needs to read the repository contents (e.g., for checking out the code), we will set `contents: read` as the minimal required permission. This block will be added at the root level of the workflow, applying to all jobs.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 24: Workflow does not contain permissions
