Chalarangelo/30-seconds-of-code

- snippets/measure-time-taken-by-function.md
Removes open curly brace in console.log in Measure time taken by function snippet
> Remove stray open curly brace

- snippets/capitalize-first-letter.md
`""[0]` -> `undefined`
`"".slice(0, 1)` -> `""`
> Capitalize first letter: safe against empty string

- snippets/factorial.md
As I commented on [reddit](https://www.reddit.com/r/javascript/comments/7j37iu/i_have_been_collecting_useful_javascript_code/dr4narm/), here's my pull request. I left the original one, was that OK?
English is not my first language so something might be wrong.
> add another way to calculate factorial

- snippets/count-occurrences-of-a-value-in-array.md
Doesn't require creation of new array as with current solution.
> Count occurrences of value in array with reduce

- snippets/last-of-list.md
Update Last of List function name to `last` to avoid confusion.
> Change last-of-list function name

- README.md
- snippets/object-from-key-value-pairs.md
I think directly returning an object from the arrow function improves readability.
> Directly return object from arrow function

- README.md
- snippets/divisible-by-number.md
With the other PR I changed the even odd number with bitwise operator. So I thought it might be useful to add a isDivisible using the modulo operator
> add a isDivisible function

- README.md
- snippets/anagrams-of-string-(with-duplicates).md
IMHO _anagrams_ snippet is AWESOME but it's kinda hard to understand for those who are new in Javascript. So, I just renamed some parameters in order simplify its complexity, and of course improve its legibility :raised_hands:
> refactor(anagrams): improve code legibility

- README.md
- snippets/pipe.md
> Added Pipe snippet

- snippets/fibonacci-array-generator.md
The fibonacci sequence being zero indexed as well as the arrays, I think we could just initialize an array with the passed length, fill it with zeroes and use the indexes for the first positions.
> minor refactor to the fibonacci array generator

- snippets/get-min-value-from-array.md
I think it shows a good use of the spread operator in variadic functions
> get minimum value from an array

- snippets/flatten-array.md
add closing bracket to the comment part
> fixing minor type bug in flatten function

- README.md
Snippet to get native type of function (lowered-case constructor name)
> Added getType function

- README.md
- snippets/run-promises-in-series.md
Running promises in series is a useful pattern
> Add "Run promises in series"

- snippets/chunk-array.md
Creates an array of elements split into groups the length of size. 
If array can't be split evenly, the final chunk will be the remaining elements.
> Add chunk array

- README.md
- snippets/bottom-visible.md
Usefull for when you need to fetch more data if user is at the bottom of the page
> Add bottomVisible

- README.md
- snippets/promisify.md
This PR adds the snipped talked in #57. Resolve #57.
> Add promisify snippet

- snippets/URL-parameters.md
- snippets/anagrams-of-string-(with-duplicates).md
- snippets/average-of-array-of-numbers.md
- snippets/count-occurrences-of-a-value-in-array.md
- snippets/deep-flatten-array.md
- snippets/flatten-array.md
- snippets/initialize-array-with-range.md
- snippets/powerset.md
- snippets/randomize-order-of-array.md
- snippets/sort-characters-in-string-(alphabetical).md
- snippets/sum-of-array-of-numbers.md
Closed issue "Array method constistency in descriptions".
> Correct array method names 

- README.md
- snippets/pick.md
similar to lodash pick method 
https://lodash.com/docs/4.17.4#pick
> add pick code snippet

- README.md
- snippets/array-difference.md
- snippets/array-intersection.md
- snippets/array-union.md
- snippets/difference-between-arrays.md
Add set operations: union, intersect and difference.
Refactor difference snippet to use Sets (`O(1)` instead of `O(n)`) and use same style as the other two set operations.
> Add set operations

- README.md
- snippets/check-for-palindrome.md
> Refactor palindrome

- README.md
- snippets/even-or-odd-number.md
In this case using `Math.abs()` is unnecessary since negative even number modulo 2 returns -0.
```
-0 === 0 // true
```
> Simplify the Even or odd number snippet

- README.md
- snippets/URL-parameters.md
Remove the Question mark as per https://github.com/Chalarangelo/30-seconds-of-code/issues/95
> Update URL Paramters snipper

- README.md
- snippets/head-of-list.md
update description to follow guide
> update description of head & ran npm run build-list

- README.md
- snippets/array-difference.md
- snippets/array-intersection.md
Internal links weren't working for Array difference and intersection due to the additional content in braces not in filename.
> Fix names and links

- snippets/sleep.md
adding a simple function similiar to sleep function in python.
useful to make delays in async functions.
> add sleep function - making delays in async functions

- README.md
- snippets/initial-of-list.md
update initial-of-list description to follow guide
> ran npm run build-list & update intial-of-list description

- README.md
- snippets/last-of-list.md
update description last-of-list to follow guide
> update last-of-list & ran npm run build-list

- README.md
use Array.from instead of Array.apply
> the chunk Array:  use Array.from instead of Array.apply

- README.md
- snippets/take.md
similar to lodash compact method
Use `.slice()` to create a slice of the array with n elements taken from the beginning.
```js
const take = (arr, n) => n === undefined ? arr.slice(0, 1) : arr.slice(0, n);
// take([1, 2, 3], 5) -> [1, 2, 3]
// take([1, 2, 3], 0) -> []
```
https://lodash.com/docs/4.17.4#take
> ran npm run build-list & add take.md

- CONTRIBUTING.md
> Fixed few grammar mistakes while reading the CONTRIBUTING.MD

- snippets/is-array.md
> Fixed is-array snippet

- snippets/number-to-array-of-digits.md
Converts a number to an array of digits.
> Added snippet to convert number to array of digits

- snippets/round-number-to-n-digits.md
> round number to n digits

- snippets/without.md
- tag_database
similar to lodash without method
Use `Array.filter()` to create an array excluding all given values
```js
const without = (arr, ...args) => arr.filter(v => args.indexOf(v) === -1)
// without[2, 1, 2, 3], 1, 2) -> [3]
// without([2, 1, 2, 3, 4, 5, 5, 5, 3, 2, 7, 7], 3, 1, 5, 2) -> [ 4, 7, 7 ]
```
https://lodash.com/docs/4.17.4#without
> Add without

- snippets/deep-flatten-array.md
https://jsperf.com/flats/1
reduce seems to be a fair bit slower ~48%.
> deep flatten array without reduce

- snippets/takeRight.md
- tag_database
similar to lodash takeRight method
Use `Array.slice()` to create a slice of the array with `n` elements taken from the end.
```js
const takeRight = (arr, n = 1) => arr.slice(arr.length - n, arr.length);
// takeRight([1, 2, 3], 2) -> [ 2, 3 ]
// takeRight([1, 2, 3]) -> [3]
// takeRight([1, 2, 3], 0) -> []
```
https://lodash.com/docs/4.17.4#takeRight
> Add takeRight

- snippets/array-includes.md
This is not working for collections because `slice()` is not allowed.
> Added snippet for array includes

- README.md
> Fix "Write json to file" link

- snippets/array-concatenation.md
> Fix array.concat snippet

- snippets/read-file-to-array.md
- tag_database
this function make an array containing each line of a file.
> adding read file to array function

- snippets/take-every-nth-element.md
- tag_database
this function works like python `list[::nth]` and it returns an array containing every nth element of a given array.
> take every nth element of an array

- snippets/clean-json-objects.md
this function removes unwanted keys from json objects deeply.
> adding function to clean json objects, deeply.

- snippets/current method name.txt
- snippets/log-method-name.md
code to get name of current method
> method name

- snippets/array-difference.md
dont think it needs it's own section (your call) but worth calling out the symmetric difference, as it's a likely next step in a set theory interview test.
> added symmetric difference note to Array difference

- .gitignore
- snippets/3-digit-hexcode-to-6-digit-hexcode.md
this update will remove code duplication in implementation and also updates explanations.
> Update 3 digit to 6 digit hexcode function

- snippets/hexcode-to-RGB.md
Hey me again. Wrote this this time; tell me what do you think.
We could have wrote this in one line, if we wouldn't have had to use `#` prefix for hexcode.
Speaking of which, I wrote also this version with alpha values. Should I create a new snippet for that (maybe `hexcode-to-RGBA.md`?) or should I add next to other one or should I update the current function with if statements to check whether or not value contains alpha segment?
```js
const hexToRgba = hex => {
const h = parseInt(hex.slice(1), 16)
return `rgba(${h >> 24}, ${(h & 0x00ff0000) >> 16}, ${(h & 0x0000ff00) >> 8}, ${(h & 0x000000ff)})`
}
// hexToRgba('#27ae60ff') -> 'rgba(39, 174, 96, 255)'
```
> Update Hexcode to RGB function with bitwise version

- snippets/extendHex.md
There was an issue with this function, I described it in #223.
Fixes: #223
> Fix extendHex.md wrong functionality

- snippets/hexToRGB.md
> Fix hexToRGB() issue with 3-digit colorcodes

- docs/index.html
- static-parts/index-start.html
Made the logo a hyperlink to the repo
> Add logo hyperlink to repo

- docs/index.html
- scripts/web-script.js
- static-parts/index-end.html
Added a "back to top" link in the footer, linking to "#top" anchor at top of <main>
> Add "back to top" in footer

- docs/index.html
- static-parts/index-start.html
See newest version ( #239 included) at http://david-wu.me/30-seconds-of-code/.
> Add subtitle to header

- README.md
- snippets/dropElements.md
fixes https://github.com/Chalarangelo/30-seconds-of-code/issues/236
> Purify drop elements

- snippets/median.md
`.sort()` mutates the original array
> Make median.md pure

- snippets/bottomVisible.md
```js
const bottomVisible = () =>
document.documentElement.clientHeight + window.scrollY >= (document.documentElement.scrollHeight || document.documentElement.clientHeight);
// bottomVisible() -> true
```
> code error

- snippets/pullAll.md
- tag_database
similar to lodash pullAll method
This method is like pull except that it accepts an array of values to filter out before Mutating and pulling all the values from the original array.
Use `Array.filter()` and `Array.includes()` to pull out the values that are not needed.
Use `Array.length = 0` to mutate the passed in array by resetting it's length to zero and `Array.push()` to re-populate it with only the pulled values.
```js
const pullAll = (arr, pullArr) => {
let pulled = arr.filter((v, i) => !pullArr.includes(v));
arr.length = 0;
pulled.forEach(v => arr.push(v));
}
// let myArray = ['a', 'b', 'c', 'a', 'b', 'c'];
// pullAll(myArray, ['a', 'c']);
// console.log(myArray) -> [ 'b', 'b' ]
```
https://lodash.com/docs/4.17.4#pullAll
> add pullAll

- snippets/select.md
Add a `select `function that retrieves a property that indicated by the selector from object.
```js
const select = (from, selector) =>
selector.split('.').reduce((prev, cur) => prev && prev[cur], from);
// const obj = {selector: {to: {val: 'val to select'}}};
// select(obj, 'selector.to.val'); -> 'val to select'
```
> [FEATURE] Add select

- snippets/pullAtValue.md
- tag_database
similar to lodash pullAt method with a slight variation explained in #245 
This method is like pull except that it accepts an array of values to filter out before Mutating and pulling all the values from the original array. Which then returns an array of removed elements.
Use `Array.filter()` and `Array.includes()` to pull out the values that are not needed.
Use `Array.length = 0` to mutate the passed in array by resetting it's length to zero and `Array.push()` to re-populate it with only the pulled values.
Use `Array.push()` to keep track of pulled values 
```js
const pullAtValue = (arr, pullArr) => {
let removed = [];
let pushToRemove = arr.forEach((v, i) => pullArr.includes(v) ? removed.push(v) : v)
let mutateTo = arr.filter((v, i) => !pullArr.includes(v))
arr.length = 0; …
```
> Add pullAtValue

- snippets/hexToRGB.md
Ref https://github.com/Chalarangelo/30-seconds-of-code/pull/204.
> Update `hexToRGB()` with additional supports and fixes

- snippets/arrayToHtmlList.md
> Snippet to convert array to HTML list items

- snippets/isArmstrongNumber.md
> Snippet for checking armstrong number

- README.md
- docs/index.html
- snippets/isPrime.md
- tag_database
Added a function that checks if the provided number is a prime number.
> A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.
> [FEATURE] add isPrime

- snippets/initialize2DArray.md
Added new snippet to initialize a 2D array by filling a value.
> Add Snippet initialize2DArray

- .github/PULL_REQUEST_TEMPLATE.md
I enhanced the PR template by adding some extra aspects, like the [ENHANCEMENT] tag or the new type of change seen here
> [Enhancement] Update PR template

- snippets/stringToArrayOfWords.md
> Snippet to convert string to array of words

- snippets/orderBy.md
> fixed an issue with default parameters

- .github/PULL_REQUEST_TEMPLATE.md
**MAKING MAINTAINABLE** #100 
Makes tracking the methods that have been UPDATED or ADDED to the lodash backlog much more easier. Than having the collaborators constantly reading all the snippets and trying to find which has been added or not. 
This way all we have to do is just look on lodash backlog timeline and whichever `methods.md` PR have been merged we can update
> Updating PULL_REQUEST_TEMPLATE.md -> Lodash Backlog

- snippets/inRange.md
> Snippet to implement inRange

- snippets/clampNumber.md
> Snippet to implement clamping

- snippets/zipObject.md
- tag_database
Add zipObject from #100 as it is one of the functions that is simple and easy to make more understandable
> [FEATURE] Add zipObject

- README.md
- snippets/pull.md
**Resolves** #258  
Mutates the original array to filter out the values specified.
Use `Array.filter()` and `Array.includes()` to pull out the values that are not needed.
Use `Array.length = 0` to mutate the passed in array by resetting it's length to zero and `Array.push()` to re-populate it with only the pulled values.
_(For a snippet that does not mutate the original array see [`without`](#without))_
```js
const pull = (arr, ...args) => {
let argState = Array.isArray(args[0]) ? args[0] : args;
let pulled = arr.filter((v, i) => !argState.includes(v));
arr.length = 0; 
pulled.forEach(v => arr.push(v));
};
// let myArray1 = ['a', 'b', 'c', 'a', 'b', 'c'];
// pull(myArray1, 'a', 'c');
// console.log(myArray1) -> [ 'b', 'b' ]
// let myArray2 = ['a', 'b', 'c', 'a', 'b', 'c'];
// …
```
> [UPDATE] pull.md -> fix hacky approach 

- README.md
- snippets/initialize2DArray.md
> Update init2d array

- snippets/httpsRedirect.md
> Snippet to perform HTTPS redirect

- README.md
- snippets/fibonacci.md
> Update fib Array() -> Array.from()

- snippets/everyNth.md
**Resolves** #299 - everyNth doesn't actually return the Nth values.
> [FIX: #299] Make everyNth return the "Nth" value.

- README.md
- snippets/isPrime.md
Improve isPrime to be O(sqrt(n)). Some tailing space is removed by IDE
> Improve isPrime to be O(sqrt(n))

- snippets/isPrime.md
> [UPDATE] Resolves #297

- static-parts/README-start.md
Added two badges to README, the [PRs welcome](http://makeapullrequest.com/) and the [Insight.io](https://insight.io/github.com/Chalarangelo/30-seconds-of-code/tree/master/?source=0) badge
> [ENHANCEMENT] Insight.io and PRs badge

- .travis/push.sh
Most of the guides I can find use the travis email and name to differentiate from user commits. This will come in handy later down the line to filter out build commits more easily. I'm pretty certain this will not break anything, but I'd like someone to take a look at it before merging.
> Update travis push

- snippets/spreadOver.md
- tag_database
Adds the spreadOver adapter allowing you to change a function from variadic to an array input
> [FEATURE] add spreadOver snippet

- snippets/flip.md
- tag_database
Added flip adapter and adapter category to tags database
I have run into a problem that when I run the builder it does not build the category
> [Feature] Add flip adapter

- README.md
- snippets/elementIsVisibleInViewport.md
- snippets/orderBy.md
_Snippet_ : elementIsVisibleInViewport
The `innerWidth` and `innerHeight` was not assigned in code snippet, so adding them.
> [BUG] Add missing line of code to elementIsVisibleInViewport

- snippets/toDecimalMark.md
changing the way toDecimalMark works to get most out of JS native functions.
> found a way more ES6ish solution for toDecimalMark

- snippets/collectInto.md
- tag_database
Add a collectInto function which is helpful if you have a lot of functions or libraries that accept arrays, but will often use them with a specified amount of arguments
> [FEATURE] add collectInto snippet

- static-parts/index-start.html
Added few missing meta tags. 
Source: https://frontendchecklist.io/
> [FEATURE] Front end checklist

- static-parts/README-start.md
> [ENHANCEMENT] License Badge

- snippets/call.md
- tag_database
Adds the call snippet which is extremely useful in composition
> [FEATURE] add call snippet

- snippets/RGBToHex.md
- snippets/arrayLcm.md
- snippets/clampNumber.md
- snippets/cleanObj.md
- snippets/collatz.md
- snippets/countVowels.md
- snippets/curry.md
- snippets/fromCamelCase.md
- snippets/getDaysDiffBetweenDates.md
- snippets/groupBy.md
- snippets/hammingDistance.md
- snippets/hexToRGB.md
- snippets/inRange.md
- snippets/initial.md
- snippets/initialize2DArray.md
- snippets/isArmstrongNumber.md
- snippets/last.md
- snippets/mapObject.md
- snippets/pick.md
- snippets/pull.md
- snippets/pullAtIndex.md
- snippets/pullAtValue.md
- snippets/sample.md
- snippets/scrollToTop.md
- snippets/select.md
- snippets/spreadOver.md
- snippets/tail.md
- snippets/toCamelCase.md
- snippets/toEnglishDate.md
- snippets/words.md
Finally, after a hard work, I hope that I didn't miss other ones.
> Fixing typos

- snippets/RGBToHex.md
- snippets/arrayLcm.md
- snippets/clampNumber.md
- snippets/cleanObj.md
- snippets/collatz.md
- snippets/countVowels.md
- snippets/curry.md
- snippets/fromCamelCase.md
- snippets/getDaysDiffBetweenDates.md
- snippets/groupBy.md
- snippets/hammingDistance.md
- snippets/hexToRGB.md
- snippets/inRange.md
- snippets/initial.md
- snippets/initialize2DArray.md
- snippets/isArmstrongNumber.md
- snippets/last.md
- snippets/mapObject.md
- snippets/pick.md
- snippets/pull.md
- snippets/pullAtIndex.md
- snippets/pullAtValue.md
- snippets/sample.md
- snippets/scrollToTop.md
- snippets/select.md
- snippets/spreadOver.md
- snippets/tail.md
- snippets/toCamelCase.md
- snippets/toEnglishDate.md
- snippets/words.md
Reverts Chalarangelo/30-seconds-of-code#325
> Revert "Fixing typos"

- snippets/flatten.md
Updated flatten to use a spread operator, updated flatten's description
> [UPDATE] Flatten updated to use ES6 spread

- README.md
- snippets/arrayLcm.md
FIX snippets/arrayLcm part syntax
> [FIX: #330][SNIPPETS] snippets arrayLcm part syntax

- snippets/repeatString.md
- snippets/toKebabCase.md
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#repeat
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#kebabCase
> ADD: toKebabCase.md and repeatString.md

- snippets/negate.md
Add negate.md snippet
**Part of** #100  
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#negate
> ADD: negate.md

- snippets/extendHex.md
useage:  Array.slice() should be changed to String.slice()
> [bug] useage: change Array.slice() for String.slice()

- snippets/detectDeviceType.md
> Snippet to detect device type

- snippets/dropRight.md
The slice function can take the negative negative value of the second agrimement
> [ENHANCEMENT] dropRight bad example 👎

- snippets/randomHexColorCode.md
> Snippet to generate random color code

- snippets/negate.md
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#negate
> [UPDATE] Fix typo in negate.md

- snippets/randomHexColorCode.md
Optimize and shorten random Hex Color Code generation snippet using random hexadecimal generation and bitshifting.
> [ENHANCEMENT] Optimize randomHexColorCode.md

- snippets/flip.md
Updates the flip example to fix the bug
Resolves #337
[ ] Website
[x] Snippets
[ ] General / Things regarding the repository (like CI Integration)
[x] Bug fix (non-breaking change which fixes an issue)
[ ] Enhancement (non-breaking improvement of a snippet)
[ ] New feature (non-breaking change which adds functionality)
[ ] Breaking change (fix or feature that would cause existing functionality to change)
[x] My code follows the code style of this project.
[x] My change requires a change to the documentation.
[ ] I have updated the documentation accordingly.
[x] I have checked that the changes are working properly
[x] I have checked that there isn't any PR doing the same
[x] I have read the CONTRIBUTING document.
> [BUGIFX] Fix the flip examples

- snippets/factorial.md
**Resolves** #156 by adding handling for negative numbers( both even and odd ), and decimal numbers( rounds to nearest as per definition of factorial ), more examples
> [BUGFIX] Factorial snippet and examples

- snippets/toKebabCase.md
> [FIX] kebabCase styling + remove global variable + handle empty string

- snippets/toCamelCase.md
- snippets/toSnakeCase.md
Updated toCamelCase and toSnakeCase as requested by @Pl4gue in #341
> [UPDATE] toCamelCase and toSnakeCase

- snippets/curry.md
a small mistake found in reading.
a small mistake found in reading.
> Fix parameter reference error in the usage

- snippets/tomorrow.md
- tag_database
> add tomorrow snippet

- snippets/cleanObj.md
I think the consistency of the format is good and necessary.
> Fix the same format as other methods

- snippets/shuffle.md
**Resolves** #357
See the issue #357 for more information.
**Lodash#shuffle** #100 -> https://lodash.com/docs/4.17.4#shuffle
> [FIX: #357] Change shuffle algorithm to Fisher-Yates shuffle

- snippets/tomorrow.md
- tag_database
#360 snippets have gone into the void for some reason.
> Recreate tomorrow snippet

- snippets/pipeFunctions.md
- snippets/randomHexColor.md
- snippets/toSnakeCase.md
Rename pipe.md and randomHexColorCode.md to match their function names after taking permission from @Chalarangelo
> [FIX] rename pipe.md and randomHexColorCode.md

- README.md
- snippets/readFileLines.md
This updates the pattern for splitting lines so that it is Windows compatible. See https://stackoverflow.com/questions/21895233/how-in-node-to-split-string-by-newline-n.
> [ENHANCEMENT] Handle CRLF for splitting lines on Windows

- scripts/lint-script.js
Replaces `.md` in the temp file name with nothing as 3 extensions seem to not make the linting run.
> [FIX] lint-script.js

- snippets/clampNumber.md
clampNumber is now a single line function
code for clampnumber too verbose, relies on assignment side effects for uneeded brevity.
> ENHANCEMENT: tightened code for clampnumber

- package-lock.json
- package.json
- scripts/lint-script.js
Makes it like 60x faster by running semistandard on the entire folder. Lints and prettifies both the function definition and example blocks
> [FIX] Hyper speed-boost lint-script to lint examples + use prettier formatting

- snippets/orderBy.md
> Make orderBy pure and fix examples

- snippets/arrayQuickSort.md
- snippets/quickSort.md
> [FEATURE] arrayQuickSort

- snippets/hasClass.md
- snippets/toggleClass.md
- tag_database
Snippets for checking and toggling classes for HTML elements, similar to jQuery's methods.
> [FEATURE] Add hasClass/toggleClass snippets (browser)

- snippets/hide.md
- snippets/show.md
- tag_database
Snippets for showing and hiding elements, similar to jQuery's methods.
> [FEATURE] Add show/hide snippets (browser)

- README.md
- docs/index.html
- snippets/getStyle.md
- snippets/hasClass.md
- snippets/setStyle.md
- snippets/toggleClass.md
- tag_database
Snippets for getting and setting the style of HTML elements, similar to jQuery's methods.
> [FEATURE] Add getStyle/setStyle snippets (browser)

- snippets/UUIDGeneratorBrowser.md
- snippets/UUIDGeneratorNode.md
- tag_database
**Resolves** #376, this time with less messups 😄 
Should I also include an example using the `uuid` module? It seems not needed, but better ask and be safe than sorry.
> [FIX: #376] Update UUIDGenerator with new examples

- .gitignore
- package-lock.json
- package.json
- scripts/tdd-script.js
> Tdd.updated

- snippets/byteSize.md
Add a snippet byteSize to calculate the byte-count of a string
> Add a snippet byteSize

- snippets/splitLines.md
- tag_database
Splits a multiline string into an array of lines
> [FEATURE] Add splitLines

- snippets/lowercaseKeys.md
- tag_database
Creates a new object from the specified object, where all the keys are in lowercase.
> [FEATURE] Add lowercaseKeys

- snippets/average.md
> [FIX] average when passing an array as an argument

- snippets/lcm.md
> [FIX] lcm.md

- README.md
- docs/index.html
- snippets/fibonacci.md
fix fibonacci example typo in Math section
> fix fibonacci example typo

- README.md
- scripts/build.js
Adds emojis to the categories and adds a horizontal rule between cats.
Ignore the README file, couldn't revert it back.. only edited the `build.js` script.
> Add emojis to README categories

- snippets/yesNo.md
- tag_database
Evaluates the answer to a yes or no `(Y/N)` question. Useful in CLI.
> [FEATURE] Add yesNo snippet

- snippets/toSnakeCase.md
> [FIX] toSnakeCase

- static-parts/README-start.md
add link to README for files to import snippets into text editors
> [FEATURE] add link to README for files to import snippets into text editors

- snippets/copyToClipboard.md
- tag_database
Snippet for copying to clipboard on modern browsers.
> [FEATURE] Add copyToClipboard

- snippets/size.md
**Lodash[ADD: size.md]** #100 -> https://lodash.com/docs/4.17.4#size
> [ADD: `size.md`] add size snippet

- snippets/memoize.md
- tag_database
Simple `memoize` snippet. Simpler than Lodash's though
**Lodash[ADD]** #100 -> https://lodash.com/docs/4.17.4#memoize
> [FEATURE] memoize snippet

- snippets/isAbsoluteURL.md
- tag_database
A snippet to check if a given string is an absolute URL.
> [FEATURE] Add isAbsoluteURL

- snippets/isPromise.md
- snippets/isPromiseLike.md
- tag_database
Adds a snippet that checks if an object looks like a Promise.
> [FEATURE] Add isPromise snippet

- snippets/elo.md
- tag_database
https://en.wikipedia.org/wiki/Elo_rating_system
> [FEATURE] Elo rating system snippet

- snippets/isArmstrongNumber.md
- snippets/standardDeviation.md
> [ENHANCEMENT] Exponent operator

- snippets/join.md
- snippets/sortedIndex.md
> [FEATURE] join.md

- snippets/hasFlags.md
- snippets/invertKeyValues.md
- snippets/isTravisCI.md
- snippets/untildify.md
- tag_database
Adds 4 popular micro-modules from the npm registry (coded by hand, inspired by actual existing modules).
> [FEATURE] Micro modules

- snippets/anagrams.md
> Add warning to anagrams

- snippets/prettyBytes.md
> [FEATURE] Add prettyBytes snippet

- snippets/cloneRegExp.md
- tag_database
> [FEATURE] cloneRegExp

- snippets/runAsync.md
- tag_database
Runs a function async-ly (with caveats)
See the note at the bottom. Can that be solved somehow?
> [FEATURE] runAsync snippet

- snippets/once.md
- tag_database
**Lodash[ADD once.md]** #100 -> https://lodash.com/docs/4.17.4#once
> [ADD `once.md`] once

- .github/ISSUE_TEMPLATE.md
- .travis/push.sh
- COLLABORATING.md
- README.md
- docs/index.html
- snippets/shuffle.md
algoritm -> algorithm
Commiting -> Committing
preferrably -> preferably
- Bug fix (non-breaking change which fixes an issue)
- My code follows the code style of this project.
- My change requires a change to the documentation.
- I have updated the documentation accordingly.
- I have checked that the changes are working properly
- I have checked that there isn't any PR doing the same
- I have read the **CONTRIBUTING** document.
> Fixed minor typos

- snippets/once.md
> [UPDATE] once.md

- snippets/sum.md
> Fixed grammar

- static-parts/README-start.md
Add ProductHunt Badge to README
> Add ProductHunt Badge to README

- snippets/solveRPN.md
Add the list of supported operators and specify that unary operators are not supported. Also tell that `^` & `**` are the same and are exponential operators(as `^` can be confused to be the xOR operator)
> Add the list of supported operator

- snippets/memoize.md
Uses a `Map` instead of a plain object to store any value as a key, and also allows access to the cache by setting a `.cache` property on the returned function.
> [UPDATE] memoize.md

- snippets/pluralize.md
Fixed a error in the description of pluralize
> Fixed an error in pluralize.md

- static-parts/README-start.md
> Better highlight the npm package + add warning

- static-parts/README-start.md
> Add CDN + Browser usage of package

- snippets/runAsync.md
- Remove `this` before `postMessage`, as some browsers prepend `"use strict";` to the blob, I think(?). It's not necessary anyway. 
- Make it a single line, because the minified version keeps the newlines of it. 
- Use `let` in example
> [UPDATE] runAsync.md

- snippets/httpsRedirect.md
One of the snippets was displaying as an example, because it had no examples, so I added one.
> [FIX] Update httpsRedirect.md

- snippets/elo.md
Allows you to pass an arbitrary number of ratings in the array.
> [UPDATE] Add multiplayer support to elo.md

- snippets/gcd.md
Aligns the styling with `lcm`.
> [UPDATE] gcd.md

- docs/mini/flavor.scss
Improves the syntax highlighting colors on the website
> Improve syntax highlighting

- snippets/initializeArrayWithRange.md
There was typo mistake in which Array.from was missing from Array(Math.ceil((end+1-start)/step) in description of snippet
> Updated initializeArrayWithRange

- snippets/digitize.md
Probably being pernickety.  But if we're using ES6, you could just use a template litoral instead of string concat? Not sure if the litoral version is a bit more difficult to read mind you.
use a string litoral instead of string concat.
> If using ES6, use template litorals

- snippets/hide.md
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#(method) 
- [-] I have referenced the `method` to the lodash backlog.
> fix hide err

- scripts/build.js
> Snippets archive

- CONTRIBUTING.md
Some conventions have changed.
> Updated styleguide

- package-lock.json
- test/isDivisible/isDivisible.test.js
- test/isEven/isEven.test.js
- test/isSorted/isSorted.test.js
- test/isString/isString.test.js
- test/isUpperCase/isUpperCase.test.js
- test/isValidJSON/isValidJSON.test.js
- test/toOrdinalSuffix/toOrdinalSuffix.test.js
- test/toSafeInteger/toSafeInteger.test.js
- test/truncateString/truncateString.test.js
- test/unescapeHTML/unescapeHTML.test.js
- test/validateNumber/validateNumber.test.js
- test/words/words.test.js
- test/yesNo/yesNo.test.js
I've added few tests cases for some of the functions. I will continue to add more of them but here are some of them for now.
> [FEATURE] Add few tests

- snippets/initialize2DArray.md
Update snippet initialize2d to use Array.from() instead of Array().fill()
> style guide fix Array().fill -> Array.from()

- test/pullAtIndex/pullAtIndex.test.js
- test/pullAtValue/pullAtValue.test.js
- test/union/union.test.js
- test/without/without.test.js
- test/zipObject/zipObject.test.js
Just submitting a PR still a lot Type test or Basic example test I have to add & I am going to add that haven't been already added.
Going to quickly do a few more. Eat some breakfast then get back to it
> Adding Type Test

- snippets/isObject.md
- tag_database
- test/decapitalize/decapitalize.js
- test/decapitalize/decapitalize.test.js
- test/flattenDepth/flattenDepth.js
- test/flattenDepth/flattenDepth.test.js
- test/isObject/isObject.js
- test/isObject/isObject.test.js
**Resolves** #531 
**Lodash[ADD]** #100 -> https://lodash.com/docs/4.17.4#isObject
> Add isObject

- snippets/colorize.md
- tag_database
Output colorization in node console is quite common, so I tried my hand on it. Should work cross-platform.
> [FEATURE] Add colorize

- snippets/parseCookie.md
- snippets/serializeCookie.md
- tag_database
Methods for code serialization/deserialization, inspired by [cookie](https://www.npmjs.com/package/cookie).
> [FEATURE] Add parseCookie and serializeCookie

- static-parts/README-start.md
Update to show both `npm` and `yarn` installations.
> [FEATURE] update readme-start.md

- snippets/equals.md
- tag_database
- test/equals/equals.js
- test/equals/equals.test.js
Similar to lodash's `isEqual` but more in line with [deep-equal](https://www.npmjs.com/package/deep-equal) and Node's [`assert.deepEqual`](https://nodejs.org/api/assert.html#assert_assert_deepequal_actual_expected_message). Included are tests for the snippet.
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#isEqual
> [FEATURE] Added equals.md and tests

- test/cleanObj/cleanObj.test.js
- test/curry/curry.test.js
- test/elo/elo.test.js
- test/factorial/factorial.test.js
Added few tests for snippets that had a problem with `tdd` script a few days ago. Slowly but surely cleaning our test log.
:white_check_mark: *489/489 passing*, safe to merge right away.
> [FEATURE]  Recursive snippets tests

- snippets/observeMutations.md
- tag_database
A method that observes mutations in the DOM and runs a callback.
> [FEATURE] Add observeMutations.md

- snippets/httpPost.md
**Resolves** #530 
When using httpPost you either must provide a null/undefined or a body. This is for not only readability, but also because a developer should always know if they want to send something.
> PATCH: HTTP Post footprint change

- snippets/sdbm.md
> Fix spelling in snippet description

- test/validateNumber/validateNumber.test.js
- test/without/without.test.js
- test/words/words.test.js
- test/yesNo/yesNo.test.js
- test/zip/zip.test.js
- test/zipObject/zipObject.test.js
> Adding test

- scripts/tdd.js
- snippets/hashBrowser.md
- snippets/hashNode.md
- tag_database
Added two snippets for generating hashes from given values/objects (one for browser, one for Node). The Browser one might be slightly advanced, but I think they are both quite valuable.
> [FEATURE] Hash methods

- snippets/atob.md
- snippets/btoa.md
- tag_database
Adds two snippets for Node, `atob` and `btoa`, similar to the browser methods [`atob`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob) and [`btoa`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa).
> [FEATURE] btoa and atob

- snippets/flip.md
Used idiomatic javascript to avoid complex array functions. The rest operator is used to collect all the remaining argument of the function. So instead of taking the whole list and then popping the first element (this is expensive), we simply retain the first argument as a variable `first` and the rest of the arguments are stored as array in `rest` variable. Then we just change the order of arguments.
I think this code is easy to grok and is much faster and more ES6.
```js
const flip = fn => (first, ...rest) => fn(...rest, first);
```
Note - 
Intentionally used the word `rest` instead of `args` because I felt for this case rest better helps people understand that , rest holds all the args after first arg. If I have used `args` then it partly implies that first is not an arg which is not …
> [ENHANCEMENT] [UPDATE: `flip.md`] Use idiomatic js for flip function 

- scripts/tdd.js
update tdd script tabbing chained methods making more readable
> update tdd script tabbing chained methods making more readable

- snippets/zipWith.md
- tag_database
**Resolves** #100 
**Lodash[ACTION]** #100 -> https://lodash.com/docs/4.17.4#zipwith
> [ADD: zipWith.md]

- snippets/delay.md
Basically that. [Here's](https://cdn.pbrd.co/images/H4DuuaT.png) a screenshot if someone wants it.
> delay.md's heading was defer

- CONTRIBUTING.md
Updated contribution guidelines to include a section for browser specific tests.
> [FIX] Documentation 

- snippets/overArgs.md
> Fix overArgs example

- snippets/isPlainObject.md
> Update isPlainObject |  typo

- test/mapObject/mapObject.test.js
add basic test for mapObject from yesterday issue
> update mapObject basic test

- snippets/runAsync.md
`fn.toString()` is implicity called when the function is interpolated in a template literal already, and it can be immediately invoked if wrapped in parens
> Shorten runAsync.md

- test/tomorrow/tomorrow.test.js
fixes failing the `npm test` command
> fix broken test in tomorrow.test.js

- snippets/debounce.md
> Simplify debounce.md

- snippets/mostPerformant.md
- tag_database
Returns the index of the best performing function (fastest)
Example wrapper utils as well.
```js
// Assumes checking fn1 is more performant than fn2
const isMorePerformant = (fn1, fn2) => mostPerformant([fn1, fn2]) === 0
```
For increased reliability, you might want to check the most frequent index when doing `mostPerformant` calls multiple times (along with high iteration count)
> Add mostPerformant snippet

- snippets/pad.md
- tag_database
- test/pad/pad.js
- test/pad/pad.test.js
Adds string padding function.
- `pad` pads on both sides
> [FEATURE] pad - string padding

- static-parts/README-start.md
The 30 seconds brand is evolving!
> Add affiliates

- snippets/smoothScroll.md
- tag_database
Smooth scrolling. Self-explanatory pretty much. It is quite a neat trick. I think this is the good addition to the project. 👍 
Tests are not provided. I will write them over the weekend.
> [FEATURE] Smooth scrolling

- snippets/isBrowser.md
- tag_database
> [FEATURE] isBrowser

- snippets/indexOfAll.md
- test/indexOfAll/indexOfAll.js
> indexOfAll in a functional way [ENHANCEMENT]]

- snippets/attempt.md
> [FIX: #638] bug in 'attempt' snippet

- snippets/is.md
> fix(is.md): use constructor property instead of instanceof

- snippets/hz.md
- tag_database
Returns the number of times a function executed per second after `iterations` times.
> [FEATURE] hz

- snippets/initializeNDArray.md
- tag_database
Create a n-dimensional array with given value.
> [FEATURE] Add initializeNDArray

- snippets/arrayToHtmlList.md
> update arrayToHtmlList to more high efficiency

- snippets/deepClone.md
- test/deepClone/deepClone.js
- test/deepClone/deepClone.test.js
Would previously create an object with indices as keys. Now properly clones as array.
**Resolves** #658
> [FIX: #658] Fixed problems with array values in deepClone snippet

- snippets/takeWhile.md
- test/takeWhile/takeWhile.js
Simplify takeWhile [ENHANCEMENT]
Use native method pop of array instead slicing and getting the last element also destructuring elements inside filter method.
> Simplify takeWhile

- tag_database
Whoops forgot to tag toHash as Array for searching(even though it's actually compatible with all Array likes
> add toHash to tag database with Array tag

- snippets/countOccurrences.md
Removes unnecessary addition of `0`.
> Update `countOccurrences` function

- snippets/elo.md
Not assigning `arr.length` to a variable in a for loop means that the read is done on every iteration.
**Resolves** #(issue number)
> ELO snippet formatting + performance

- README.md
- snippets/matchesWith.md
- snippets/unflattenObject.md
- Use `obj[key] === source[key]` replace `obj[key] == source[key]` in the methods of `matchesWith` in `Object`
- Use `Unflatten` replace `Unlatten` in the methods of `unflattenObject` in `Object`
**Resolves** #(issue number)
> fix type and make equals consistency

- glossary/Element.md
I'm curious if this works well enough. Should there also be a way for us to include optional examples?
This is a disambiguation article for the Glossary about what a JS Element is
> #690 create Element glossary for disambiguation

- glossary/Cross-site-scripting-xss.md
- glossary/Cross-site-scripting.md
- glossary/DOM.md
- glossary/Functional-programming.md
- glossary/Promise.md
- glossary/Recursion.md
Added few items to our glossary.
> [ENHANCEMENT] Glossary

- glossary/Functor.md
> [Glossary] Functor

- snippets/indexOfAll.md
- test/indexOfAll/indexOfAll.js
Simplify indexOfAll [ENHANCEMENT]
Use native method reduce instead of array looping.
> Simplify indexOfAll

- snippets/indexOfAll.md
It returned a function that accepted the same arguments again that when run again with the same inputs would eventually result
**Resolves** #(issue number)
> indexOfAll.md returns a functions with shadow vars

- scripts/analyze.js
- scripts/build.js
- scripts/extract.js
- scripts/glossary/keyword.js
- scripts/glossary/library.js
- scripts/lint.js
- scripts/localize.js
- scripts/module.js
- scripts/rollup.js
- scripts/tag.js
- scripts/tdd.js
- scripts/util.js
- scripts/web.js
> [CODACY] Scripts linted

- snippets/allEqual.md
- tag_database
- test/allEqual/allEqual.js
- test/allEqual/allEqual.test.js
I added the necessary files documenting the the `allEqual` function including sufficient tests.
Resolves #700
> [FEATURE] Added allEqual + tests

- snippets/average.md
- test/average/average.js
Simplify average [ENHANCEMENT]
No need to create new array inside average func
Use native method reduce instead of array looping.
> Simplify average

- snippets/bind.md
- test/bind/bind.js
Get rid of arguments for bind [ENHANCEMENT]
Soon arguments will be deprecated
Use native method reduce instead of array looping.
> Get rid of arguments for bind

- snippets/bindKey.md
- test/bindKey/bindKey.js
Get rid of arguments for bindKey [ENHANCEMENT]
Soon arguments will be deprecated
> Get rid of arguments for bindKey

- snippets/longestItem.md
- test/longestItem/longestItem.js
Changed longestItem function to run in O(n) rather than O(nlog(n)).
Note: The longest item returned will now be the last one in the array rather than an unspecified one (since Array.sort is not necessarily stable).
> [ENHANCEMENT] Optimized Longest Item function

- snippets/rearg.md
- test/rearg/rearg.js
I have simplified the rearg snippet so that it's easier to understand in 30 seconds.  
The simplified version is also more powerful - it now also support duplication of arguments & extension in the number of arguments.  I didn't add tests/examples for this new functionality (yet) since I wasn't sure if we would want to commit to these additional features in the future.
I have read the contributing guidelines, but it was not clear to me if I needed to open an issue before submitting this minor change.  I apologize in advance if I made this or some mistake in the process.
> [ENHANCEMENT] Simplified Rearg Snippet

- snippets/isArrayLike.md
- test/initializeArrayWithRange/initializeArrayWithRange.js
- test/isArrayLike/isArrayLike.js
Simplied isArrayLike to directly check if the given input is iterable rather than indirectly by checking if the spread operator throws an exception.
This code is shamelessly stolen from https://stackoverflow.com/questions/18884249/checking-whether-something-is-iterable
> [ENHANCEMENT] Simplified isArrayLike

- snippets/longestItem.md
- test/longestItem/longestItem.js
- test/longestItem/longestItem.test.js
In continuation of #711, here is the updated snippet and the additional tests that we need.
> Updated longestItem + tests

- snippets/nthElement.md
- test/nthElement/nthElement.js
Simplified the implementation of nth Element to avoid unnecessary branching.
Updated documentation to reflect reality - the function would return undefined (not []) if the index was not in range.  This is maintained in the current implementation.
> [ENHANCEMENT] Simplified nth Element

- glossary/Argument.md
- glossary/Constant.md
- glossary/ES6.md
- glossary/Express.md
- glossary/Function.md
- glossary/Git.md
- glossary/HTML.md
- glossary/IP.md
- glossary/Npm.md
- glossary/React.md
- glossary/Repository.md
- glossary/Variable.md
- glossary/Yarn.md
In continuation of the development of #690.
List of terms (13):
- Variable
- Constant
- NPM
- Yarn
- Express
- React
- Git
- Repository
- Argument
- Function
- ES6
- IP
- HTML
> [GLOSSARY] Glossary additions

- snippets/formatDuration.md
- test/formatDuration/formatDuration.js
Use destructuring and template string for formatDuration [ENHANCEMENT]
Destructuring simplifies reading and understanding of the code
> Use destructuring and template string for formatDuration

- snippets/hide.md
- test/hide/hide.js
Simplify hide [ENHANCEMENT]
No need to use destructuring because of modification of each element in the input array
> Simplify hide

- glossary/AJAX.md
- glossary/CORS.md
- glossary/Closure.md
- glossary/Domain-name-registrar.md
- glossary/Flexbox.md
- glossary/Garbage-collection.md
- glossary/MongoDB.md
- glossary/Mutabe-value.md
- glossary/PWA.md
- glossary/SQL-injection.md
- glossary/SSL.md
- glossary/Scope.md
After a short workathon with @Chalarangelo we are finishing up Glossary terms for #690. Refer to commit history and files for terms added.
> Glossary terms v2

- snippets/inRange.md
- test/inRange/inRange.js
Simplify inRange [ENHANCEMENT]
Destructuring helps to make swap easily
> Simplify inRange

- snippets/intersectionBy.md
- test/intersectionBy/intersectionBy.js
Simplify intersectionBy [ENHANCEMENT]
No need to use arrow function in b.map callback
> Simplify intersectionBy

- snippets/objectFromPairs.md
- test/objectFromPairs/objectFromPairs.js
Simplify objectFromPairs [ENHANCEMENT]
It is possible here to use array destructuring of argument
> Simplify objectFromPairs

- test/deepFreeze/deepFreeze.test.js
Resolve #728 
Add unit tests for deepFreeze [ENHANCEMENT]
BTW I'm sure that `!obj[prop] instanceof Object` will be always falsy
> Add unit tests for deepFreeze

- snippets/pipeLog.md
> [FEATURE] Create pipeLog.md

- .github/PULL_REQUEST_TEMPLATE.md
In reference to #730
New PR template. Issue templates in #750.
> New template for PRs

- snippets/indentString.md
- tag_database
- test/indentString/indentString.js
- test/indentString/indentString.test.js
Inspired by [indent-string](https://www.npmjs.com/package/indent-string), I decided to submit a snippet that does what the name says for the most part.
Tests could be a bit more robust. 
Based on downloads alone, I think this is worth adding to the codebase.
**PS:** The PR template is too complex, I am already working on a new one, so kindly ignore the fact that I am not using it for this PR.
> Add indentString

- test/indexOfAll/indexOfAll.test.js
changed 'Returns all indices of val in an array' to 'When val is not found, return an empty array' for test that searches for val in an array without val
Resolves #766
> [FIX] change test comments in indexOfAll.test.js

- test/triggerEvent/triggerEvent.js
Simplify triggerEvent [ENHANCEMENT]
No need to use `undefined` as default property
> Simplify triggerEvent

- docs/scss/style.scss
- snippets_archive/isSimilar.md
- test/isSimilar/isSimilar.js
ENHANCEMENT
Ternary Operation Simplification
> Minor Simplification

- snippets/triggerEvent.md
Change docs for triggerEvent [ENHANCEMENT]
Sorry I accidentally committed only code, here comes docs
> Change docs for triggerEvent [ENHANCEMENT]

- snippets/isDuplexStream.md
- snippets/isReadableStream.md
- snippets/isStream.md
- snippets/isWritableStream.md
- tag_database
- test/isDuplexStream/isDuplexStream.js
- test/isDuplexStream/isDuplexStream.test.js
- test/isReadableStream/isReadableStream.js
- test/isReadableStream/isReadableStream.test.js
- test/isStream/isStream.js
- test/isStream/isStream.test.js
- test/isWritableStream/isWritableStream.js
- test/isWritableStream/isWritableStream.test.js
- test/takeRightWhile/takeRightWhile.js
Inspired by [is-stream](https://www.npmjs.com/package/is-stream). 
**Note:** We could add 3 additional snippets for readable, writable and duplex (read+write) streams.
> Add isStream

- snippets/btoa.md
- test/btoa/btoa.js
Fix error introduced in PR #800.
> [FIX] Error with new in btoa

- snippets/JSONtoCSV.md
Changed "demiliter" to "delimiter" in line 5
Resolves #817
> [FIX] Fixed typo

- glossary/ShadowDOM.md
- glossary/WebComponents.md
I've added glossary descriptions for Web Components and Shadow DOM. :)
> Update glossary terms

- snippets/unionBy.md
- test/unionBy/unionBy.js
Simplify unionBy [ENHANCEMENT]
No need to use arrow function
> Simplify unionBy

- snippets/palindrome.md
This pull request is an attempt to fix Issue - Resolves #833. 
Corrected the second toLowerCase() function typo and tried to make the description more clear.
> Correct palindrome.md description

- snippets/countBy.md
- test/countBy/countBy.js
Simplify countBy [ENHANCEMENT]
Remove unnecessary index argument
> Simplify countBy

- snippets/isPrimitive.md
> Another primitive assert function

- snippets/differenceBy.md
- test/differenceBy/differenceBy.js
Simplify differenceBy [ENHANCEMENT]
No need to use arrow function here
> Simplify differenceBy

- snippets/getColonTimeFromDate.md
Resolves #869 
Changed Date.prototype.toString() to Date.prototype.toTimeString()
> [FIX] wrong comment with getColonTimeFromDate #869

- snippets/isValidJSON.md
I modify the `obj` to `str` because this function is to validate a JSON string but not an object.
> [FIX] Make description and example better

- snippets/sum.md
Add a simple example `sum(1, 2, 3, 4)` in `sum.md`
> Add a simple example for sum

- snippets/tomorrow.md
- test/tomorrow/tomorrow.js
- test/tomorrow/tomorrow.test.js
As discussed in #775, `tomorrow.js` is hard to read. I’ve updated the implementation to simplify things.
I’ve removed the boolean parameter `long`. It’s a code smell and only adds to the complexity of the function. We should encourage folks to use a different method to add a prefix/suffix to a string. 
- [✅ ] Snippets, Tests & Tags (new snippets, **updated snippets**, re-tagging of snippets, added/updated tests)
- [✅] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
> [FIX] Improve the readability of tomorrow.js (solves #775)

- snippets/deepClone.md
- test/deepClone.test.js
> Fix deepClone edge case

- snippets_archive/levenshteinDistance.md
Repair levenshtein distance code block
> [FIX] Repair levenshtein distance code block

- snippets/differenceBy.md
- test/differenceBy.test.js
> [FIX] differenceBy

- test/JSONToDate.test.js
`JSONToDate()` test about timezone
> [FIX] JSONToDate test about timezone

- glossary/HTTP-and-HTTPS.md
- glossary/README.md
- snippets/compactWhitespace.md
- snippets/detectDeviceType.md
- snippets/uniqueElementsBy.md
- snippets/uniqueElementsByRight.md
Fixed some typos found by [tfb](https://github.com/schneiderl/tfb) - a typo fixing bot.
> Fixed typos

- snippets/detectDeviceType.md
> docs: fix typo

- scripts/web.js
For accessibility and general information we should add a `title` and `aria-label` attribute to the corner. So far I did not directly find any reference to the colors.
> Add aria-label and title

- snippets/uniqueElementsByRight.md
The description of `uniqueElementsByRight` was indentical to the description of `uniqueElementsBy` 
- [x ] General, Typos, Misc. & Meta (everything else, typos, general stuff and meta files in the repository - e.g. the issue template)
- [x ] I have read the guidelines in the [CONTRIBUTING](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md) document.
> [FIX] copy/paste typo in uniqueElementsByRight

- snippets/checkProp.md
remove Extra line break
remove Extra line break
> FIX Extra line break

- test/chainAsync.test.js
- test/collectInto.test.js
- test/debounce.test.js
- test/delay.test.js
- test/hashNode.test.js
- test/runPromisesInSeries.test.js
- test/sleep.test.js
Some expectations involving asynchronous tests were not working. By default, Jest tests complete once they reach the end of their execution. If there are assertions on asynchronous code, but we don't make Jest aware of it, those tests will simply pass.
There are specific ways to make Jest wait for expectations:
For callback-based code, we can introduce the `done` argument on each test. This is a callback function provided by Jest. Each test will wait for this callback to be executed after the desired assertions are done. If the `done` callback is not invoked, the test will timeout.
For promise-based code, we can simply return the promise from the test and use run the expectations on the `then`. Or we can use the `resolves` / `rejects` helpers.
Finally, we can use also async / await, by …
> fix(tests): expectations of some async test where not working

- snippets/mapObject.md
We may also want to mention the edge case of more complex operations in another PR
Resolves #951
> Clarify that keys are being stringified

- README.md
- static-parts/README-start.md
- static-parts/about.html
- Since the `30-seconds-python` and `30-seconds-php` have been part of the `30-seconds`, it's time to update the statuses of these two link in `Related projects` section in `README`.
- Update the current GitHub project links for these two repositories.
> [ENHANCEMENT] Remove unofficial message because they're official

- snippets/isWeekday.md
- tag_database
- test/isWeekday.test.js
- Add the `isWeekday` code snippets.
> [FEATURE] Add isWeekday code snippets

- snippets/isWeekend.md
- tag_database
- test/isWeekend.test.js
- Add `isWeekend` code snippets.
> [FEATURE] Add isWeekend code snippets

- README.md
Fix the error link of 30 Seconds of CSS.
- [] Other (please specifiy in the description above)
> [FIX] Update the link of 30 Seconds of CSS

- snippets/hasKey.md
- test/hasKey.test.js
Added a new snippet, `hasKey`, that checks if a given path exists within a JSON object.
> Add a new snippet, hasKey

- snippets/objectToQueryString.md
- test/objectToQueryString.test.js
Added new utility snippet `objectToQueryString` which generates query string from key-value pairs from given object.
Also added tests for the snippet. There are no braking changes.
> [FEATURE] Add new objectToQueryString utility snippet and it's unit tests

- snippets/includesAny.md
- test/includesAny.test.js
Added a new snippet, `includesAny`, that checks if an array includes at least one element of a given list.
> add includesAny

- snippets/includesAll.md
- test/includesAll.test.js
Added a new snippet, `includesAll`, that checks if an array includes all elements of a given list.
> add includesAll

- snippets/copyToClipboard.md
- snippets/hasKey.md
- snippets/permutations.md
- snippets/stringPermutations.md
Fix some snippets that would break the new website. Nothing major, just swapping around some content.
> Fix breaking snippets

- snippets/ary.md
> Fix a mistype in ary

- test/getType.test.js
Thank you for your comments.
https://github.com/30-seconds/30-seconds-of-code/pull/1045
I understood there was a problem with my code.
And I felt the test code needed an additional case.
> Add "getType" test case

- snippets/head.md
- snippets/last.md
- test/head.test.js
- test/last.test.js
Update head to check on empty, undefined, null array.
So you you can guard against uncatched errors
> [ENHANCEMENT] Updates `head` and `last` to type check

- snippets/pull.md
Just a small change but I discovered that the variable i isn't used in 
```javascript
let pulled = arr.filter((v, i) => !argState.includes(v));
```
so I changed the line to 
```javascript
let pulled = arr.filter(v => !argState.includes(v));
```
> [FIX] Update pull.md

- snippets/checkProp.md
Wrong function name: checkProps -> checkProp
> fix: Wrong function name: checkProps -> checkProp

- snippets/ary.md
- snippets/call.md
- snippets/collectInto.md
- snippets/flip.md
- snippets/over.md
- snippets/overArgs.md
- snippets/pipeAsyncFunctions.md
- snippets/pipeFunctions.md
- snippets/promisify.md
- snippets/rearg.md
- snippets/spreadOver.md
- snippets/unary.md
Merge `Adapter` category into `Function` category.
> Remove adapter

- snippets/isContainedIn.md
Hi there,
I've made two minor changes to the snippet below. 
1. The word "occurences" was wrong, fixed it to "occurrences".
2. The word "amount" reads weird here. Since we are counting an exact number I believe that going with the word "number" reads better. Even if you search for "amount of occurrences" on google you will find very few occurrences.
Thank you for the great project.
> isContainedIn.md: rewrite descrpition

- CONTRIBUTING.md
Update typo `begginer` -> `beginner` in the contributing guidelines
> [FIX] update typo

- snippets/toSnakeCase.md
> [FIX] typo

- snippets/objectToPairs.md
- snippets/toPairs.md
- snippets_archive/objectToEntries.md
- test/toPairs.test.js
> Update object to pairs

- snippets/mapObject.md
Resolves #1092. First time contributor to this repo so let me know if there's any updates to be made.
> [FIX] update implementation & explanation for mapObject

- snippets/isLeapYear.md
Reopened from #1083 to remove changes to package.json.
> add isLeapYear snippet

- snippets/vectorAngle.md
Added a new snippet that calculates angle between two vectors.
> added snippet VectorAngle

- snippets/forEachRight.md
> Update: update forEachRight.md

- snippets/last.md
as per [discussion](https://twitter.com/30secondsofcode/status/1280479521788047360)
> use `instanceof` to determine if arg is an array

- snippets/last.md
according to https://github.com/30-seconds/30-seconds-of-code/pull/1165#pullrequestreview-446823247
> use isArray instead of instanceof

- snippets/symmetricDifferenceBy.md
Added another example with an array of objects
> Update symmetricDifferenceBy.md: add another example

- snippets/flattenObject.md
> Solved Issue #1176

- snippets/reverseNumber.md
This is a code snippet to reverse a number in javascript.
> reverse number snippet added

- snippets/dayName.md
Add dayName to retrieve the name of the weekday
> Add dayName

- snippets/slugify.md
- snippets/yesterday.md
I also changed a `let` to a `const` in `yesterday.md` as per the [Snippet guidelines](https://github.com/30-seconds/30-seconds-of-code/blob/master/CONTRIBUTING.md%23snippet-guidelines).
> Add slugify

- snippets/isDuplicates.md
A simple but useful check for duplicate values snippet.
> Add isDuplicates

- snippets/detectLanguage.md
Comes in handy to detect the language of the user to set is as default preference.
> Add detectLanguage.md

- snippets/xor.md
Logical xor Using basic or (`||`), and (`&&`), not (`!`) operators.
> Added xor.md

- snippets/getProtocol.md
This PR adds a new snippet getProtocol that returns the protocol being used on the current page.
> Added getProtocol

- snippets/addDaysToDate.md
Adding new JavaScript code for adding days to a given date
> Adding addDaysToDate snippet

- snippets/toHSLArray.md
_aNgElOs hOw dO I GeT FrEe t-sHiRt_
Based on this [discussion](https://github.com/30-seconds/30-seconds-of-code/pull/1555#issuecomment-708540518) I am adding a `toHSLArray` implementation. Technically it's the same thing as the `toRGBArray` but new content is new content 🤷‍♂️ 
More ways for users to find what they wanted either through our search or through organic traffic.
> add toHSLArray

- snippets/allUnique.md
Check for uniqueness in an array
Returns `true`  if all the values in an array are unique, and vice versa
> Added allUnique snippet

- snippets/milesToKm.md
> Fix variable name in milesToKm

- snippets/pluck.md
> feat: implementation of underscore pluck function

- snippets/findKeys.md
A snippet for returns keys that match the given value in an object. Thanks for your time to review!
> feat: add findKeys snippet

- snippets/compactObject.md
accept for hacktoberfest please... thank you
btw this is my first to contribute... ✌
any advice is accepted
> feat: add compactObject snippet

- snippets/nor.md
adding a logical nor operation in javascript
`nor(true,true); // false`
`nor(true,false); // false`
`nor(false,true); // false`
`nor(false,false); // true`
PS: it's my first contribution ever, please pardon me if any mistakes, and give me chance to correct them if any.
> added nor snippet

- snippets/toCamelCase.md
Update `toCamelCase` snippet to use `const` instead of `let`.
> Update toCamelCase snippet to use const instead of let

- snippets/hide.md
As-is, this snippet produces a `TypeError`.  See commit comment for details.
> fix snippets/hide.md

- snippets/addEventListenerAll.md
The function created isn't the function that was called. I corrected the function call
> Corrected function call

- snippets/toPascalCase.md
Added toPascalCase, a snippet that changes the given string to Pascal Case.
> Add toPascalCase

- .github/labeler.yml
- .github/workflows/label.yml
Add [Labeler](https://github.com/marketplace/actions/labeler) action.
> Add labeler action

- CONTRIBUTING.md
- snippets/js/s/event-loop-explained.md
> fixes typo

- src/components/Footer.astro
Fix Footer spaces between elements
resolve #1994 issue
> footer space style fix

- content/snippets/js/s/value-frequencies.md
Replacing ternary condition using nullish coalescing operator.
> refactor: modify condition based on es2020

- src/components/Footer.astro
Before:
After:
**Which change I done ?**
- I have resolve FooterPage setting path so that It's working Perfect !!
Fixes :#2029
Please Checkout My PR If have any issue let me know .
> Fix/ footer setting path And URL redirection
